### ISSUE TITLE
DateTime field not handled by facade

### ISSUE THREAD

**Issue by HavelTheRawk** [tylernathanreed/nova-field-manager#2]
The DateTime nova field does not seem to be supported by the _Field_ facade. When using _DateTime::make()_ , the creation and index pages load correctly. However, when using _Field::DateTime()_ , the following exception occurs.
![image](https://user-images.githubusercontent.com/36083480/65073058-b09d6d00-d957-11e9-90d2-3a7d03cebb8c.png)

Here is the code in my resource that is causing the problem:
```
use Field;
use Laravel\Nova\Fields\DateTime;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;

public function fields(Request $request)
{
    return [
        ID::make()->sortable(), // Works
        Text::make('Key', 'display_name'), // Works
        Field::text('System Name', 'system_name'), //Works
        Field::DateTime('Created At', 'created_at'), // Fails
        DateTime::make('Updated At', 'updated_at'), // Works
    ];
}
```

Here's the first portion of the Telescope stack trace:
```
message: "Call to undefined method DateTime::make()",
exception: "Symfony\Component\Debug\Exception\FatalThrowableError",
file: "E:\Code\FilingCabinet\vendor\reedware\nova-field-manager\src\NovaFieldManager.php",
line: 49,
```

**Comment by tylernathanreed** [comment]
@HavelTheRawk 

The method call is case sensitive. The method you should be using is `dateTime`. If you would like to be able to use `DateTime` instead, you can leverage the configuration file that comes with the listing of default Nova fields out of the box.
